services:
  container:
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 15000:3306
    container_name: institute_container
    volumes:
      - ~/project:/var/lib/mysql
    image: mysql